# Generated by Django 6.0.5 on 2026-06-02 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('spring', 'Primavera'), ('summer', 'Estate'), ('autumn', 'Autunno'), ('winter', 'Inverno')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tag_type', models.CharField(choices=[('diet', 'Regime alimentare'), ('allergen', 'Allergene')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='salt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='saturated_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugars',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vegetable_subcategory',
            field=models.CharField(blank=True, choices=[('leafy', 'Ortaggi a foglia'), ('root', 'Radici'), ('tuber', 'Tuberi'), ('flower', 'Ortaggi a fiore'), ('fruit_veg', 'Ortaggi a frutto'), ('bulb', 'Bulbi'), ('stem', 'Ortaggi a fusto'), ('legume', 'Legumi')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='core.seasonentry'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='core.tag'),
        ),
    ]
