# Generated by Django 6.0.5 on 2026-06-03 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seasonentry_tag_ingredient_fiber_ingredient_salt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weekplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekplan',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekplan',
            name='name',
            field=models.CharField(blank=True, help_text='Nome del piano, es: "Piano proteico 2000kcal"', max_length=100),
        ),
        migrations.AddField(
            model_name='weekplan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='week_start',
            field=models.DateField(blank=True, help_text='Lunedì della settimana — null per piani template', null=True),
        ),
        migrations.RemoveField(
            model_name='weekplan',
            name='user',
        ),
    ]
