# Generated by Django 6.0.5 on 2026-06-12 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_weekplan_unique_together_meal_is_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='diet_style',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_carbs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_fat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_kcal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_protein',
        ),
        migrations.CreateModel(
            name='NutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='es. "Bulk 2800kcal", "Definizione vegana"', max_length=100)),
                ('target_kcal', models.PositiveIntegerField(default=2000)),
                ('target_protein', models.PositiveIntegerField(default=150, help_text='grammi')),
                ('target_carbs', models.PositiveIntegerField(default=200, help_text='grammi')),
                ('target_fat', models.PositiveIntegerField(default=70, help_text='grammi')),
                ('diet_style', models.CharField(choices=[('none', 'Nessuno'), ('vegetarian', 'Vegetariano'), ('vegan', 'Vegano'), ('pescatarian', 'Pescatariano')], default='none', max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='weekplan',
            name='nutrition_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='week_plans', to='core.nutritiontarget'),
        ),
    ]
