# Generated by Django 4.2.7 on 2026-06-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_diet_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSlotTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='% del totale giornaliero (0-100)', max_digits=5, null=True)),
                ('kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('protein', models.PositiveIntegerField(blank=True, help_text='grammi', null=True)),
                ('carbs', models.PositiveIntegerField(blank=True, help_text='grammi', null=True)),
                ('fat', models.PositiveIntegerField(blank=True, help_text='grammi', null=True)),
                ('meal_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_targets', to='core.mealslot')),
                ('nutrition_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_targets', to='core.nutritiontarget')),
            ],
            options={
                'unique_together': {('nutrition_target', 'meal_slot')},
            },
        ),
    ]
