# Generated by Django 4.2.7 on 2026-06-17 09:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_nutrition_target_created_weekplan_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Es. Famiglia Rossi', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.household')),
                ('linked_user', models.ForeignKey(blank=True, help_text='Opzionale: collegamento a un account (futuro).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='grams',
            field=models.DecimalField(decimal_places=1, help_text='Porzione di riferimento (base). Per pasti famiglia: grammi effettivi per persona in MealIngredientMemberPortion.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='WeekPlanSlotAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_attendances', to='core.householdmember')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.weekplanslot')),
            ],
            options={
                'unique_together': {('slot', 'household_member')},
            },
        ),
        migrations.CreateModel(
            name='MealIngredientMemberPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredient_portions', to='core.householdmember')),
                ('meal_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_portions', to='core.mealingredient')),
            ],
            options={
                'unique_together': {('meal_ingredient', 'household_member')},
            },
        ),
    ]
