# Generated by Django 4.2.7 on 2026-06-17 10:12

from django.db import migrations, models
import django.db.models.deletion


def assign_legacy_targets_to_first_member(apps, schema_editor):
    NutritionTarget = apps.get_model('core', 'NutritionTarget')
    Household = apps.get_model('core', 'Household')
    HouseholdMember = apps.get_model('core', 'HouseholdMember')
    linked_owners = set()
    qs = NutritionTarget.objects.filter(
        owner_id__isnull=False,
        is_system=False,
        household_member_id__isnull=True,
    ).order_by('-created_at')
    for nt in qs:
        if nt.owner_id in linked_owners:
            continue
        h = Household.objects.filter(owner_id=nt.owner_id).first()
        if not h:
            continue
        m = HouseholdMember.objects.filter(household=h).order_by('sort_order', 'id').first()
        if not m:
            continue
        linked_owners.add(nt.owner_id)
        nt.household_member_id = m.id
        nt.save(update_fields=['household_member_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_household_and_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiontarget',
            name='household_member',
            field=models.ForeignKey(blank=True, help_text='Se impostato, il target è riferito a questo commensale; deve appartenere al nucleo del planner (owner).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_targets', to='core.householdmember'),
        ),
        migrations.RunPython(assign_legacy_targets_to_first_member, noop_reverse),
    ]
