# Generated by Django 4.2.7 on 2026-06-17 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_nutrition_target_household_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, help_text='Opzionale: promemoria (es. più carboidrati post-workout).', max_length=240)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WeekPlanDayKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('day_profile', models.ForeignKey(blank=True, help_text='Vuoto = giorno non etichettato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_plan_day_assignments', to='core.dayprofile')),
                ('week_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_kinds', to='core.weekplan')),
            ],
            options={
                'unique_together': {('week_plan', 'day')},
            },
        ),
    ]
