# Generated by Django 4.2.7 on 2026-06-17 12:32

from django.db import migrations, models
import django.db.models.deletion


def copy_nt_household_member_to_member_fk(apps, schema_editor):
    NutritionTarget = apps.get_model('core', 'NutritionTarget')
    HouseholdMember = apps.get_model('core', 'HouseholdMember')
    # Ordine cronologico: se esistono più NT con lo stesso membro, vince l'ultimo creato.
    for nt in NutritionTarget.objects.exclude(household_member_id=None).order_by('created_at'):
        HouseholdMember.objects.filter(pk=nt.household_member_id).update(nutrition_target_id=nt.id)


def restore_nt_household_member_from_member_fk(apps, schema_editor):
    NutritionTarget = apps.get_model('core', 'NutritionTarget')
    HouseholdMember = apps.get_model('core', 'HouseholdMember')
    for m in HouseholdMember.objects.exclude(nutrition_target_id=None).order_by('id'):
        nt = NutritionTarget.objects.filter(pk=m.nutrition_target_id).first()
        if nt is None:
            continue
        if getattr(nt, 'household_member_id', None) is None:
            NutritionTarget.objects.filter(pk=nt.pk).update(household_member_id=m.id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_day_profile_and_week_plan_day_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='nutrition_target',
            field=models.ForeignKey(
                blank=True,
                help_text='Target attivo per questo commensale; più persone possono condividere lo stesso target.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='linked_household_members',
                to='core.nutritiontarget',
            ),
        ),
        migrations.RunPython(copy_nt_household_member_to_member_fk, restore_nt_household_member_from_member_fk),
        migrations.RemoveField(
            model_name='nutritiontarget',
            name='household_member',
        ),
    ]
