# Generated by Django 4.2.7 on 2026-06-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_member_nutrition_target_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayProfileMemberModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('protein_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('carbs_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('fat_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                (
                    'day_profile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='member_modifiers',
                        to='core.dayprofile',
                    ),
                ),
                (
                    'household_member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='day_modifiers',
                        to='core.householdmember',
                    ),
                ),
            ],
            options={
                'unique_together': {('day_profile', 'household_member')},
            },
        ),
    ]
