# Generated by Django 6.0.5 on 2026-09-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_weekplanslot_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayprofile",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Optional reminder (e.g. more carbs after a workout).",
                max_length=240,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("protein", "Protein"),
                    ("vegetable", "Vegetable"),
                    ("carb", "Carbohydrate"),
                    ("fat", "Fat"),
                    ("dairy", "Dairy"),
                    ("fruit", "Fruit"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="vegetable_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leafy", "Leafy greens"),
                    ("root", "Roots"),
                    ("tuber", "Tubers"),
                    ("flower", "Flower vegetables"),
                    ("fruit_veg", "Fruit vegetables"),
                    ("bulb", "Bulbs"),
                    ("stem", "Stem vegetables"),
                    ("legume", "Legumes"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealslottarget",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="% of the daily total (0-100)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mealslottarget",
            name="protein",
            field=models.PositiveIntegerField(blank=True, help_text="grams", null=True),
        ),
        migrations.AlterField(
            model_name="seasonentry",
            name="name",
            field=models.CharField(
                choices=[
                    ("spring", "Spring"),
                    ("summer", "Summer"),
                    ("autumn", "Autumn"),
                    ("winter", "Winter"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(
                choices=[("diet", "Diet"), ("allergen", "Allergen")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="weekplan",
            name="name",
            field=models.CharField(
                blank=True,
                help_text='Plan name, e.g. "High-protein 2000 kcal"',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="weekplan",
            name="week_start",
            field=models.DateField(
                blank=True,
                help_text="Monday of the week — null for template plans",
                null=True,
            ),
        ),
    ]
