# Generated by Django 6.0.5 on 2026-09-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_reclassify_chickpeas_and_lentils_as_proteins"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("category", "vegetable"), _negated=True),
                    models.Q(("vegetable_subcategory", ""), _negated=True),
                    _connector="OR",
                ),
                name="core_vegetables_require_macro_category",
            ),
        ),
    ]
