# Generated by Django 6.0.5 on 2026-09-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ingredient_core_vegetables_require_macro_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekplanslot',
            name='skipped',
            field=models.BooleanField(default=False, help_text='Marked as "no meal planned" — excluded from the day\'s expected macros.'),
        ),
    ]
