"""Household dishes, grouped by genre. Grams in the spec are per shared plate."""
from .models import MealGenre as G

# Shorthand from the handwritten list → catalog name.
INGREDIENT_ALIASES = {
    'pasta': 'Pasta di semola',
    'zucchina': 'Zucchine',
    'zucchine': 'Zucchine',
    'ricotta': 'Ricotta',
    'salmone affumicato': 'Salmone affumicato',
    'zucca': 'Zucca',
    'coniglio': 'Coniglio',
    'salsa': 'Salsa di pomodoro',
    'sugo': 'Salsa di pomodoro',
    'salsa di pomodoro': 'Salsa di pomodoro',
    'parmigiano': 'Parmigiano',
    'parmigianos': 'Parmigiano',
    'pomodorino': 'Pomodorini',
    'pomodorini': 'Pomodorini',
    'seppie': 'Seppie',
    'melanzana': 'Melanzana',
    'melenzane': 'Melanzana',
    'tonno sgocciolato': 'Tonno al naturale',
    'limone': 'Limone',
    'cipolla': 'Cipolla',
    'burro': 'Burro',
    'patata': 'Patata',
    'scamorza': 'Scamorza',
    'lardo': 'Lardo',
    'pancetta': 'Pancetta',
    'funghi': 'Funghi champignon',
    'fungo champignon': 'Funghi champignon',
    'funghi champignon': 'Funghi champignon',
    'prosciutto crudo': 'Prosciutto crudo',
    'prosciutto': 'Prosciutto cotto',
    'prosciutto cotto': 'Prosciutto cotto',
    'besciamella': 'Besciamella',
    'salmone': 'Salmone',
    'aglio': 'Aglio',
    'olio': "Olio d'oliva",
    'peperoncino': 'Peperoncino',
    'pangrattato': 'Pangrattato',
    'prezzemolo': 'Prezzemolo',
    'cappero': 'Capperi',
    'capperi': 'Capperi',
    'olive': 'Olive verdi',
    'olive verdi': 'Olive verdi',
    'olive nere': 'Olive nere',
    'acciughe': 'Acciughe',
    'peperone': 'Peperone',
    'peperoni': 'Peperone',
    'peperone rosso': 'Peperone rosso',
    'peperone giallo': 'Peperone giallo',
    'peperone verde': 'Peperone verde',
    'stracchino': 'Stracchino',
    'uovo': 'Uova intere',
    'uova': 'Uova intere',
    'pecorino': 'Pecorino',
    'guanciale': 'Guanciale',
    'philadelphia protein': 'Philadelphia protein',
    'philadelphia': 'Philadelphia protein',
    'rucola': 'Rucola',
    'legumi': 'Legumi misti cotti',
    'porro': 'Porro',
    'macinato di pollo': 'Macinato di pollo',
    'macinato': 'Macinato di manzo',
    'datterino rosso': 'Datterino rosso',
    'datterino giallo': 'Datterino giallo',
    'pomodorino verde': 'Pomodorino verde',
    'avocado': 'Avocado',
    'spinaci': 'Spinaci',
    'noci': 'Noci',
    'mandorle': 'Mandorle',
    'tortellini': 'Tortellini',
    'panna': 'Panna',
    'salvia': 'Salvia',
    'trofie': 'Trofie',
    'pesto': 'Pesto',
    'mozzarella': 'Mozzarella',
    'riso': 'Riso basmati',
    'riso basmati': 'Riso basmati',
    'mais': 'Mais',
    'pollo': 'Petto di pollo',
    'lattuga': 'Lattuga',
    'pomodoro': 'Pomodoro',
    'cous cous': 'Couscous',
    'couscous': 'Couscous',
    'curry': 'Curry',
    'carota': 'Carota',
    'gnocchi di patate': 'Gnocchi',
    'gnocchi': 'Gnocchi',
    'pane integrale': 'Pane integrale',
    'finocchio': 'Finocchio',
    'arancia': 'Arancia',
    'farina': 'Farina',
    'insalata mista': 'Insalata mista',
    'insalata': 'Insalata mista',
    'ketchup': 'Ketchup',
    'miele': 'Miele',
    'salsa di soia': 'Salsa di soia',
    'anacardi': 'Anacardi',
    'hamburger di tacchino': 'Hamburger di tacchino',
    'tacchino': 'Petto di tacchino',
    'piadina': 'Piadina',
    'senape': 'Senape',
    'senape in grani': 'Senape in grani',
    'tonno fresco': 'Tonno fresco',
    'piselli': 'Piselli',
    'ravanelli': 'Ravanelli',
    'patata dolce': 'Patata dolce',
    'gamberi': 'Gamberi',
    'asparago': 'Asparagi',
    'asparagi': 'Asparagi',
    'yougurt greco': 'Yogurt greco 0%',
    'yogurt greco': 'Yogurt greco 0%',
    'yogurt greco 0%': 'Yogurt greco 0%',
    'cetriolo': 'Cetriolo',
    'pesce spada': 'Pesce spada',
    'pinoli': 'Pinoli',
    'purè': 'Purè di patate',
    'aceto': 'Aceto',
    'mix soffritto': 'Mix soffritto',
    'braciola': 'Braciola',
    'salsiccia': 'Salsiccia',
    'hamburger di manzo': 'Hamburger di manzo',
    'manzo': 'Manzo magro',
    'vitella': 'Vitello',
    'broccolo': 'Broccoli',
    'broccoli': 'Broccoli',
    'fesa di tacchino': 'Petto di tacchino',
    'pane tipo 00': 'Pane tipo 00',
    'robiola': 'Robiola',
    "salsa all'aglio": "Salsa all'aglio",
    'scalogno': 'Scalogno',
    'formaggio stagionato': 'Formaggio stagionato',
    'tahina': 'Tahina',
    'farro': 'Farro',
    'orzo': 'Orzo perlato',
    'verdura foglia larga': 'Verdure a foglia larga',
    'erba cipollina': 'Erba cipollina',
    'cipollotto': 'Cipollotto',
    'pane di segale': 'Pane di segale',
    'semi': 'Semi misti',
    'cavolo cappuccio': 'Cavolo cappuccio',
    'cavolo rosso': 'Cavolo rosso',
    'cavolfiore': 'Cavolfiore',
    'pesca': 'Pesca',
    'melone': 'Melone',
    'verdure cotte': 'Verdure cotte',
    'busta di risotto': 'Risotto in busta',
    'merluzzo': 'Merluzzo',
    'sedano': 'Sedano',
    'barbabietola': 'Barbabietola',
    'radicchio': 'Radicchio',
    'fiocchi di latte': 'Fiocchi di latte',
    'feta': 'Feta',
    'bresaola': 'Bresaola',
    'quinoa': 'Quinoa',
    '150 pomodorino': 'Pomodorini',
    '50 cipollotto': 'Cipollotto',
}

# (genre, display name, comma-separated shorthand; a trailing number is grams)
RECIPES = (
    # Pasta / Cereali
    (G.PASTA_CEREALI, 'Pasta e Zucchina', 'pasta, zucchina 200, ricotta'),
    (G.PASTA_CEREALI, 'Pasta Zucchina e Latte', 'pasta, zucchina 200, ricotta'),
    (G.PASTA_CEREALI, 'Pasta Zucchina e Salmone', 'pasta, zucchina 200, salmone affumicato'),
    (G.PASTA_CEREALI, 'Pasta e Zucca', 'pasta, zucca 200, coniglio'),
    (G.PASTA_CEREALI, 'Pasta al Sugo', 'pasta, salsa 200, parmigiano'),
    (G.PASTA_CEREALI, 'Pasta Olio e Parmigiano', 'pasta, parmigiano'),
    (G.PASTA_CEREALI, 'Pasta Pomodorini', 'pasta, pomodorino 200, seppie'),
    (G.PASTA_CEREALI, 'Pasta Melanzana', 'pasta, melanzana 200, ricotta'),
    (G.PASTA_CEREALI, 'Pasta Tonno e Limone', 'pasta, tonno sgocciolato, limone'),
    (G.PASTA_CEREALI, 'Pasta Tonno e Cipolla', 'pasta, tonno sgocciolato, cipolla 200'),
    (G.PASTA_CEREALI, 'Pasta Burro e Limone', 'pasta, burro, limone'),
    (G.PASTA_CEREALI, 'Pasta e Patate', 'pasta, patata, scamorza, lardo'),
    (G.PASTA_CEREALI, 'Pasta e Pancetta', 'pasta, pancetta'),
    (G.PASTA_CEREALI, 'Pasta alla Ricotta', 'pasta, ricotta'),
    (G.PASTA_CEREALI, 'Pasta ai Funghi', 'pasta, funghi 200, prosciutto crudo'),
    (G.PASTA_CEREALI, 'Pasta Besciamella e Salmone', 'pasta, besciamella, salmone'),
    (G.PASTA_CEREALI, 'Pasta Maradona', 'pasta, aglio, olio, peperoncino, pangrattato, prezzemolo, cappero, olive'),
    (G.PASTA_CEREALI, 'Pasta Aglio, Olio e Peperoncino', 'pasta, aglio, olio, peperoncino, tonno sgocciolato'),
    (G.PASTA_CEREALI, 'Pasta alla Ghiotta', 'pasta, salsa, acciughe, olive verdi'),
    (G.PASTA_CEREALI, 'Pasta Peperoni', 'pasta, peperone 200, stracchino'),
    (G.PASTA_CEREALI, 'Pasta alla Carbonara', 'pasta, uovo, pecorino, guanciale'),
    (G.PASTA_CEREALI, 'Pasta e Salmone', 'pasta, salmone affumicato'),
    (G.PASTA_CEREALI, 'Pasta Philadelphia e Salume', 'pasta, philadelphia protein, prosciutto crudo'),
    (G.PASTA_CEREALI, 'Pasta al Pesto di Rucola e Pomodorini', 'pasta, rucola 200, parmigiano, pomodorino'),
    (G.PASTA_CEREALI, 'Pasta e Lenticchie', 'pasta, legumi'),
    (G.PASTA_CEREALI, 'Pasta ai Porri', 'pasta, porro 200, macinato di pollo'),
    (G.PASTA_CEREALI, 'Pasta Datterina', 'pasta, datterino rosso 80, datterino giallo 80, olive nere 40, prosciutto crudo'),
    (G.PASTA_CEREALI, 'Pasta al Pesto di Avocado e Noci', 'pasta, avocado 100, spinaci 100, noci, parmigiano, limone'),
    (G.PASTA_CEREALI, 'Tortellini Panna, Burro e Prosciutto', 'tortellini, burro, prosciutto cotto'),
    (G.PASTA_CEREALI, 'Tortellini Salsa', 'tortellini, salsa 200, macinato'),
    (G.PASTA_CEREALI, 'Tortellini Burro e Salvia', 'tortellini, burro, salvia'),
    (G.PASTA_CEREALI, 'Trofie al Pesto', 'trofie, pesto 45, mozzarella'),
    (G.PASTA_CEREALI, 'Riso in bianco', 'riso, parmigiano'),
    (G.PASTA_CEREALI, 'Riso Pomodorini ed Olive', 'riso, pomodorino 150, olive 50, parmigiano'),
    (G.PASTA_CEREALI, 'Riso e Zucchine', 'riso, zucchina 100, ricotta'),
    (G.PASTA_CEREALI, 'Riso pronto', 'riso, busta di risotto'),
    (G.PASTA_CEREALI, 'Insalata di Riso', 'riso, tonno sgocciolato, mais 80, olive 40, pomodorino 80'),
    (G.PASTA_CEREALI, 'Insalata di Riso e Pollo', 'riso, pollo, olive 40, pomodoro 80, lattuga 80'),
    (G.PASTA_CEREALI, 'Riso e Verdure', 'riso, zucchina 70, peperone giallo 70, melanzana 70, uova'),
    (G.PASTA_CEREALI, "Riso fritto all'Aglio", 'riso, parmigiano, aglio'),
    (G.PASTA_CEREALI, 'Cuscus con Verdure', 'cous cous, peperone rosso 70, zucchina 70, cipolla 70'),
    (G.PASTA_CEREALI, 'Cuscus di Curry e Peperone', 'cous cous, curry, peperone rosso 200, parmigiano'),
    (G.PASTA_CEREALI, 'Cuscus Marocchino', 'cous cous, carota 100, peperone giallo 100, legumi'),
    (G.PASTA_CEREALI, 'Insalata di Pasta Salmone, Philadelphia e Prezzemolo', 'pasta, salmone, philadelphia protein, prezzemolo'),
    (G.PASTA_CEREALI, 'Insalata di Pasta con Rucola e Limone', 'pasta, rucola 60, pomodorino 140, limone'),
    (G.PASTA_CEREALI, 'Gnocchi al sugo', 'gnocchi di patate, sugo 200'),
    (G.PASTA_CEREALI, 'Gnocchi alla sorrentina', 'gnocchi di patate, pomodorino 200, mozzarella 40'),
    # Pollo / Tacchino
    (G.POLLO_TACCHINO, 'Piatto con verdure e pollo', 'pollo, cipolla 50, carota 50, zucchina 50, pomodoro 50, peperone rosso 50'),
    (G.POLLO_TACCHINO, 'Pollo e zucchine', 'pollo, zucchina 200'),
    (G.POLLO_TACCHINO, 'Pollo al curry con riso basmati', 'pollo, riso basmati, curry'),
    (G.POLLO_TACCHINO, 'Pollo e Spinaci', 'pollo, spinaci 200'),
    (G.POLLO_TACCHINO, 'Pollo ed Insalata', 'pollo, lattuga 50, mais 80, cipolla 70'),
    (G.POLLO_TACCHINO, 'Pollo, Pomodorini e Mais', 'pollo, pomodorino 100, mais 100'),
    (G.POLLO_TACCHINO, 'Pollo al Limone con Rucola', 'pollo, limone, rucola 80'),
    (G.POLLO_TACCHINO, 'Pollo e Verdure', 'pollo, zucchina 70, peperone 70, melanzana 70'),
    (G.POLLO_TACCHINO, 'Pollo e Patate', 'pollo, patata, cipolla 200'),
    (G.POLLO_TACCHINO, 'Pollo con Champignon e Broccoli', 'pollo, fungo champignon 100, broccolo 100'),
    (G.POLLO_TACCHINO, 'Pollo e Peperoni', 'pollo, peperone rosso 100, peperone giallo 100'),
    (G.POLLO_TACCHINO, 'Caesar salad croccante con straccetti di Pollo', 'pollo, pane integrale, lattuga 100'),
    (G.POLLO_TACCHINO, 'Spinacine di Pollo', 'pollo, spinaci 200'),
    (G.POLLO_TACCHINO, 'Pollo arrosto ed Insalata di Agrumi', 'pollo, finocchio 100, arancia 100'),
    (G.POLLO_TACCHINO, 'Polpette di pollo', 'pollo, farina, insalata mista 100'),
    (G.POLLO_TACCHINO, 'Pollo in agrodolce con Riso Basmati', 'pollo, farina, ketchup, miele, salsa di soia, riso basmati, peperone rosso 400'),
    (G.POLLO_TACCHINO, 'Tacchino saltato con Anacardi', 'tacchino, anacardi, peperone rosso 200'),
    (G.POLLO_TACCHINO, 'Hamburger di Tacchino con Verdure saltate', 'hamburger di tacchino, zucchina 100, cipolla 100'),
    (G.POLLO_TACCHINO, 'Sandwich di Tacchino, Pomodori e Lattuga', 'tacchino, pomodoro 100, lattuga 50'),
    (G.POLLO_TACCHINO, 'Wrap proteico', 'piadina, philadelphia, pollo, senape, insalata 80'),
    (G.POLLO_TACCHINO, 'Panino Pulled Pork', 'pollo, insalata 200, salsa di pomodoro 100'),
    # Pesce
    (G.PESCE, 'Merluzzo, Pomodorini e Olive', 'merluzzo, pomodorino 150, olive nere 50'),
    (G.PESCE, 'Merluzzo e Cipolle stufate', 'merluzzo, cipolla 200'),
    (G.PESCE, 'Tonno e Patate', 'tonno sgocciolato, patata'),
    (G.PESCE, 'Tonno e Piselli', 'tonno fresco, piselli'),
    (G.PESCE, 'Salmone e Patate', 'salmone, patata, rucola 100'),
    (G.PESCE, 'Salmone ed Insalata', 'salmone, insalata 100'),
    (G.PESCE, 'Pesce e Patate bollite', 'merluzzo, patata, carota 200'),
    (G.PESCE, 'Pesce e Zucchine', 'merluzzo, zucchina 200'),
    (G.PESCE, 'Pesce e mix di Verdure', 'merluzzo, pomodoro 50, zucchina 50, melanzana 50, cipolla 50'),
    (G.PESCE, 'Pesce alla Ghiotta', 'merluzzo, salsa, capperi, olive verdi 100'),
    (G.PESCE, 'Pesce e Piselli', 'merluzzo, piselli'),
    (G.PESCE, 'Ciotola al Tonno', 'tonno fresco, riso, sedano 100, ravanelli 100'),
    (G.PESCE, 'Filetto di Salmone con Verdure al forno', 'salmone, patata dolce, zucchina 200'),
    (G.PESCE, 'Filetto di Merluzzo in camicia', 'cous cous, merluzzo, carota 100, mais 100, piselli'),
    (G.PESCE, 'Gamberetti ed Asparagi', 'gamberi, asparago 200'),
    (G.PESCE, 'Fish and chips con Verdure arrosto', 'patata, merluzzo, broccolo 100, carota 100'),
    (G.PESCE, 'Merluzzo gratinato con Pomodorini', 'merluzzo, pomodorino 200, pangrattato, olive verdi 50'),
    (G.PESCE, 'Bistecca di Tonno con salsa ai Cetrioli', 'tonno fresco, yougurt greco, cetriolo 200'),
    (G.PESCE, 'Filetto di Tonno con Spinaci e salsa allo Yogurt', 'tonno fresco, yougurt greco, spinaci 200'),
    (G.PESCE, 'Pesce spada alla Siciliana', 'pesce spada, pomodorino 150, olive verdi 20, pinoli'),
    (G.PESCE, 'Cotolette di Tonno', 'zucchina 200, tonno sgocciolato, patata, pangrattato'),
    (G.PESCE, 'Insalata di Zucchine e Salmone affumicato', 'salmone affumicato, zucchina 200'),
    # Carni rosse
    (G.CARNI_ROSSE, 'Polpette di macinato', 'macinato, pangrattato, insalata 100'),
    (G.CARNI_ROSSE, 'Polpette di macinato con purè', 'macinato, pangrattato, purè'),
    (G.CARNI_ROSSE, 'Trita e funghi', 'macinato, funghi 200'),
    (G.CARNI_ROSSE, 'Trita e Rucola', 'macinato, rucola 100, senape in grani, aceto'),
    (G.CARNI_ROSSE, 'Trita e Piselli', 'macinato, piselli'),
    (G.CARNI_ROSSE, 'Trita alla salsa di soia con insalata', 'macinato, salsa di soia, insalata 100'),
    (G.CARNI_ROSSE, 'Trita e Salsa', 'macinato, salsa 100, mix soffritto'),
    (G.CARNI_ROSSE, 'Braciole', 'braciola'),
    (G.CARNI_ROSSE, 'Salsiccia', 'salsiccia'),
    (G.CARNI_ROSSE, 'Hamburger', 'hamburger di manzo, insalata 100, pomodoro 100'),
    (G.CARNI_ROSSE, 'Bistecca rucola e parmigiano', 'manzo, rucola 100, parmigiano'),
    (G.CARNI_ROSSE, 'Bistecca e pomodorini', 'manzo, rucola 100, pomodorino 100'),
    (G.CARNI_ROSSE, 'Pirofila di carne macinata con patate', 'patata, macinato, mozzarella'),
    (G.CARNI_ROSSE, "Scaloppine di Vitello all'Arancia con Broccoli Stufati", 'vitella, arancia 100, farina, broccolo 100'),
    # Insaccati
    (G.INSACCATI, 'Prosciutto e Spinaci', 'prosciutto, spinaci 200'),
    (G.INSACCATI, 'Salume e Insalata', 'bresaola, insalata 80, pomodorini 100'),
    (G.INSACCATI, 'Involtini di Peperoni e Fesa', 'peperone rosso 100, fesa di tacchino, lattuga 80'),
    (G.INSACCATI, 'Pomodorini, Mozzarella e Bresaola', 'pomodorino 200, mozzarella, bresaola'),
    (G.INSACCATI, 'Fesa, Rucola e Pomodori', 'fesa di tacchino, rucola 80, pomodorino 100'),
    (G.INSACCATI, 'Lasagne di Zucchine e Prosciutto', 'prosciutto cotto, zucchina 200, pangrattato'),
    (G.INSACCATI, 'Panino integrale con Peperone rosso, Cetriolo e Grana', 'pane integrale, peperone rosso 100, cetriolo 100, parmigiano'),
    (G.INSACCATI, 'Panino Bresaola, Rucola e Parmigiano', 'pane tipo 00, bresaola, rucola 80, parmigiano'),
    (G.INSACCATI, "Panino Cotto, Robiola, salsa all'Aglio, Insalata", "pane integrale, robiola, salsa all'aglio, insalata 80"),
    # Uova
    (G.UOVA, 'Uova e Pomodorini', 'uova, pomodorino 200'),
    (G.UOVA, 'Uova e Spinaci', 'uova, spinaci 200'),
    (G.UOVA, 'Uova e Patate', 'uova, patata, carota 200'),
    (G.UOVA, 'Uova Rucola e Pomodori', 'uova, rucola 80, pomodorino 100'),
    (G.UOVA, 'Uova e mix di Verdure', 'uova, zucchina 100, porro 100'),
    (G.UOVA, 'Omelette ai Funghi', 'uova, funghi 200'),
    (G.UOVA, 'Insalata di Uova, Porri e Zucchina', 'uova, porro 100, zucchina 100'),
    (G.UOVA, 'Uova, Pomodoro, Zucchine', 'uova, pomodoro 100, zucchina 100'),
    (G.UOVA, 'Pane Tostato con Uova e Pesto', 'pane integrale, uova, pesto 45'),
    (G.UOVA, 'Uova strapazzate e Salsa', 'uova, salsa 150'),
    (G.UOVA, 'Frittata Pomodori ed Avocado', 'uova, pomodorino 100, avocado 100'),
    (G.UOVA, 'Frittata Pomodoro e Cipolla', 'uova, pomodoro 100, cipolla 100'),
    (G.UOVA, 'Salade Nicoise', 'patata, uova, lattuga 50, peperone rosso 50, pomodoro 50, cipolla 50'),
    (G.UOVA, 'Shakshuka', 'uova, cipolla 70, peperone rosso 70, salsa di pomodoro 70'),
    (G.UOVA, 'Eggs and Veggies breakfast bowl', 'broccolo 200, patata dolce, uova'),
    # Legumi
    (G.LEGUMI, 'Fajolao', 'legumi, cipolla 200'),
    (G.LEGUMI, 'Piselli, farro e scalogno', 'farro, scalogno 200, formaggio stagionato, legumi'),
    (G.LEGUMI, 'Stufato di ceci', 'legumi, cipolla 70, zucchina 70, pomodorino 70'),
    (G.LEGUMI, 'Funghi saltati con purea di ceci', 'funghi 200, legumi'),
    (G.LEGUMI, 'Insalata di Farro', 'farro, peperone 100, mais 100, parmigiano'),
    (G.LEGUMI, 'Hummus e pane Arabo', 'legumi, tahina, insalata 80'),
    (G.LEGUMI, 'Polpette di legumi', 'legumi, pangrattato, salsa di pomodoro 100'),
    (G.LEGUMI, 'Pizza di lenticchie', 'legumi, broccolo 100, peperone 100'),
    (G.LEGUMI, 'Patate Dolci, Spinaci e Crema di Cannellini', 'patata dolce, spinaci 200, legumi'),
    (G.LEGUMI, 'Insalata di ceci', 'legumi, rucola 50, mais 50, cipolla 50, pomodorino 50'),
    (G.LEGUMI, 'Insalata di Fagioli', 'legumi, pomodoro 100, cipolla 100, limone'),
    (G.LEGUMI, 'Insalata di Fagioli alla Romana', 'legumi, cipolla 200'),
    (G.LEGUMI, 'Zuppa di Orzo e Legumi', 'orzo, legumi, verdura foglia larga 200'),
    (G.LEGUMI, 'Zuppa di Farro e Lenticchie', 'farro, legumi, verdura foglia larga 200'),
    (G.LEGUMI, 'Zuppa di Legumi', 'legumi, verdura foglia larga 200'),
    (G.LEGUMI, 'Pasta con i ceci', 'legumi, pasta'),
    (G.LEGUMI, 'Pasta con i fagioli', 'legumi, pasta'),
    (G.LEGUMI, 'Pasta con le lenticchie', 'legumi, pasta'),
    # Verdura
    (G.VERDURA, 'Patate e Cipolle', 'patata, cipolla 200, ricotta'),
    (G.VERDURA, 'Spinaci e Funghi Philadelphia', 'spinaci 200, funghi 100, philadelphia protein'),
    (G.VERDURA, 'Verdure al forno', 'peperone rosso 70, zucchina 70, cipolla 70, patata, aglio, robiola'),
    (G.VERDURA, 'Curry di Melanzana e Patate', 'curry, patata, melanzana 200, prosciutto crudo'),
    (G.VERDURA, 'Torte di Patate schiacciate ai Funghi', 'patata, farina, funghi 200, robiola'),
    (G.VERDURA, 'Tortino di Patate e Spinaci', 'patata, spinaci 200, ricotta'),
    (G.VERDURA, 'Cuscus con Verdure saltate', 'cous cous, peperone giallo 70, patata, melanzana 70, pomodorino 70, parmigiano'),
    (G.VERDURA, 'Barchette di Melanzana al forno', 'melanzana 100, feta, pomodorino 100, tahina, limone'),
    (G.VERDURA, 'Ratatouille finta', 'zucchina 70, peperone 70, melanzana 70, prosciutto cotto'),
    (G.VERDURA, "Cavolfiore all'arancia", 'cavolfiore 150, arancia 100, fesa di tacchino'),
    (G.VERDURA, 'Ajvar con pane', 'peperone rosso 100, melanzana 100, pane integrale, bresaola'),
    (G.VERDURA, 'Melanzane grigliate con patè di Noci', 'melanzana 200, noci, ricotta'),
    (G.VERDURA, 'Patate in Padella con Prosciutto e Verdure', 'patata, prosciutto cotto, carota 100, zucchina 100'),
    (G.VERDURA, 'Zucca e Patate', 'zucca 200, patata, mozzarella'),
    (G.VERDURA, 'Patatine di Zucca al Forno', 'zucca 200, pangrattato, yogurt greco 0%'),
    (G.VERDURA, 'Cotolette di Melanzane e Pomodorini', 'melanzana 100, pomodorino 100, pangrattato, feta'),
    (G.VERDURA, 'Passato di Verdure', 'carota 10, scalogno 10, sedano 10, patata, porro 60, pomodorino 60, zucchina 60, prosciutto crudo'),
    (G.VERDURA, 'Torta in forno di Patate e Melanzane', 'patata, melanzana 200, prosciutto cotto'),
    (G.VERDURA, 'Patate al forno con Mozzarella e Spinaci', 'patata, spinaci 200, mozzarella'),
    (G.VERDURA, 'Frittelle di Verdure con Lattuga', 'zucchina 70, patata, carota 70, cipolla 70, uova, pangrattato'),
    (G.VERDURA, 'Rotoloni di Verdure', 'patata, carota 200, prosciutto cotto'),
    (G.VERDURA, 'Insalata asiatica di Cuscus', 'cous cous, melanzana 200, mandorle, yogurt greco 0%'),
    (G.VERDURA, 'Insalata di Cetrioli e Patate', 'cetriolo 200, patata, ricotta'),
    (G.VERDURA, 'Insalata di Patate con Crescione', 'patata, cipolla 50, funghi champignon 100, ravanelli 50, rucola 50'),
    (G.VERDURA, 'Insalata verde di Patate', 'patata, spinaci 100, peperone rosso 70, cipollotto 70, limone'),
    # Formaggio
    (G.FORMAGGIO, 'Involtini di Melanzane con Ricotta, Noci e pesto di Rucola', 'melanzana 400, ricotta, noci, rucola 20'),
    (G.FORMAGGIO, 'Ricotta, Spinaci e Funghi', 'ricotta, spinaci 100, funghi 100'),
    (G.FORMAGGIO, 'Panini Robiola, Insalata, Pomodori, Cipolla', 'robiola, insalata 80, pomodoro 70, cipolla 70'),
    (G.FORMAGGIO, 'Verdure arrostite con crema di Ricotta', 'patata, peperone rosso 70, zucchina 70, cipolla 70, ricotta'),
    (G.FORMAGGIO, 'Melanzane e Zucchine grigliate con crema di Ricotta', 'melanzana 100, zucchina 100, ricotta'),
    (G.FORMAGGIO, 'Frittelle di Zucchine e Carote con Yogurt', 'carota 100, zucchina 100, yogurt greco'),
    (G.FORMAGGIO, 'Focaccia di Patate con Emmental', 'patata, farina, mozzarella, zucchina 200'),
    # Zuppe
    (G.ZUPPE, 'Zuppa di funghi', 'funghi 200, parmigiano'),
    (G.ZUPPE, 'Zuppa Zucca, erba Cipollina, Carota e Grana', 'zucca 100, erba cipollina, carota 100, parmigiano'),
    (G.ZUPPE, 'Zuppa di Melanzana con Patate', 'melanzana 200, patata, philadelphia protein'),
    (G.ZUPPE, 'Zuppa di Carote', 'carota 100, zucca 100, robiola'),
    (G.ZUPPE, 'Zuppa di Pomodoro', 'pomodoro 200, stracchino'),
    (G.ZUPPE, 'Zuppa di Zucchine', 'zucchina 200, tahina, parmigiano'),
    (G.ZUPPE, 'Zuppa di Spinaci', 'spinaci 200, philadelphia protein'),
    (G.ZUPPE, 'Zuppa di Cavolfiore', 'cavolfiore 200, formaggio stagionato'),
    (G.ZUPPE, 'Zuppa di Cavolo Rosso', 'cavolo rosso 200, robiola'),
    (G.ZUPPE, 'Zuppa di Cipolle', 'cipolla 200, formaggio stagionato'),
    (G.ZUPPE, 'Vellutata di Barbabietola', 'barbabietola 200, patata, fiocchi di latte'),
    (G.ZUPPE, 'Vellutata di Spinaci', 'spinaci 200, philadelphia protein'),
    (G.ZUPPE, 'Vellutata di Cipolle', 'cipolla 200, fiocchi di latte, farina'),
    (G.ZUPPE, 'Vellutata di Zucchine', 'zucchina 100, gamberi, cipolla 100, erba cipollina'),
    (G.ZUPPE, 'Vellutata di Radicchio', 'radicchio 100, cipolla 100, patata, fiocchi di latte'),
    (G.ZUPPE, 'Vellutata di Carote', 'carota 200, fiocchi di latte'),
    # Insalate
    (G.INSALATE, 'Insalata greca', 'pomodorino 50, feta, cipollotto 50, cipolla 50, cetriolo 50'),
    (G.INSALATE, 'Insalata caprese', 'pomodoro 200, mozzarella'),
    (G.INSALATE, 'Insalata di Avocado, Cipollotti, Pomodorini e Mais', 'avocado 50, cipollotto 50, pomodorino 50, mais 50, salmone affumicato'),
    (G.INSALATE, 'Insalata di Mais messicana', 'peperone verde 70, cipolla 70, feta, mais 70'),
    (G.INSALATE, 'Insalata croccante', 'insalata 80, pomodorino 70, carota 70, parmigiano, pane di segale'),
    (G.INSALATE, 'Insalata di finocchi, arance e semi', 'finocchio 200, arancia 100, semi, formaggio stagionato'),
    (G.INSALATE, 'Insalata di cavolo e carote', 'cavolo cappuccio 70, carota 70, cipollotto 70, yougurt greco'),
    (G.INSALATE, 'Insalata autunnale', 'rucola 80, zucca 120, bresaola'),
    (G.INSALATE, 'Insalata di farro con ricotta', 'farro, carota 50, cetriolo 50, ravanelli 50, rucola 50, ricotta'),
    (G.INSALATE, 'Insalata di Pollo', 'pollo, insalata 50, pomodorino 50, mais 50, cipolla 50'),
    (G.INSALATE, 'Insalata di Pollo con Rucola', 'pollo, rucola 50, pomodorino 50, mais 50, cipolla 50'),
    (G.INSALATE, 'Insalata di Pollo Estiva', 'pollo, cipolla 70, limone, patata, olive 70, sedano 70'),
    (G.INSALATE, 'Insalata di lattuga, avocado e peperoni', 'insalata 50, avocado 100, peperoni 100, formaggio stagionato'),
    (G.INSALATE, 'Insalata greca classica', 'cetriolo 50, pomodoro 50, cipolla 50, olive nere 50, feta'),
    (G.INSALATE, 'Insalata Café de Paris', 'insalata 100, pollo, uova, olive verdi'),
    (G.INSALATE, 'Insalata di farro, pomodori, olive e pecorino', 'farro, pomodorino 150, cipollotto 50, olive'),
    (G.INSALATE, 'Insalata di riso con pomodorini, feta e olive', 'riso, olive, pinoli, feta, pomodorino 200'),
    (G.INSALATE, 'Insalata di pomodori e pesche', 'pomodoro 100, pesca 100, cipolla 50, quinoa, formaggio stagionato'),
    (G.INSALATE, 'Insalata di pomodori e cereali', 'cous cous, datterino rosso 50, datterino giallo 50, pomodorino verde 50, pomodoro 50, mozzarella'),
    (G.INSALATE, 'Insalata di mozzarella e frutta', 'mozzarella, pesca 100, melone 100, rucola 100, noci'),
    (G.INSALATE, 'Insalata pantesca', 'patata, cipolla 75, pomodorino 75, olive nere 50, prosciutto cotto'),
    (G.INSALATE, 'Carpaccio di zucchine', 'parmigiano, pinoli, zucchine 200'),
    # Piadine
    (G.PIADINE, 'Piada Tonno e Pomodori', 'piadina, tonno sgocciolato, verdure cotte 100, pomodorino 100'),
    (G.PIADINE, 'Piada Prosciutto e Parmigiano', 'piadina, prosciutto cotto, verdure cotte 100, parmigiano'),
    (G.PIADINE, 'Piada integrale, Crescenza, Fesa', 'piadina, stracchino, verdure cotte 100, fesa di tacchino'),
    (G.PIADINE, 'Piada Bresaola', 'piadina, bresaola, verdure cotte 100, parmigiano'),
    (G.PIADINE, 'Piada Melanzana, Funghi, Formaggio', 'piadina, verdure cotte 100, philadelphia protein'),
)

RECIPE_NAMES = tuple(row[1] for row in RECIPES)
